title: DevNKN's Blog
author: DevNKN
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Willing to bring my own projects to life here on GitHub!

# social links
github_username: DevNKN

show_excerpts: true # set to false to remove excerpts on the homepage

# I'll be soon working on a forum and comment section.
